### ISSUE TITLE
[enhancement] Set the slug in the frontmatter

### ISSUE THREAD

**Issue by bntzio** [tscanlin/next-blog#1]
Hi, Tim! 👋

It'd be really awesome if users could specify the /slug in the Front Matter of each post 🙂

What do you think?

**Comment by tscanlin** [comment]
Hey, I have a PR where I've implemented this here:
https://github.com/tscanlin/next-blog/pull/2

It works fine for me except for static exporting but I think I have a weird env issue going on. Can you try out the `custom-paths` branch or look at the PR and see if this works for you.

I chose `paths` instead of slug incase people want to define multiple paths (aliases) for a page which I always though would be a nice feature especially for people migrating their website.

**Comment by bntzio** [comment]
Nice! Just tried it out, it works very well, however, when I access a custom path defined in the markdown file (`/first-post`) by clicking the `next/link`:

```
<Link href={`post?fullUrl=${post.href}`} as={post.href}>
  <h2>{post.title}</h2>
</Link>
```

I get an error saying that **Cannot find module './content/first-post.json'.** but when I access the `/first-post` URL directly it works.

**Comment by tscanlin** [comment]
Hmm, what if you just try making the href the actual href? '/First-post'

Also try passing filePath as the query parameter instead of fullUrl, I just kept that in place to preserve existing functionality for now.

**Comment by bntzio** [comment]
Just making the href `/first-post` it does redirect to the post but with a 404, if I refresh it works.

In where do I pass filePath?

**Comment by tscanlin** [comment]
FilePath is a query parameter just like fullUrl.

I see intermittent 404s before the page loads too, but when I do next export it works fine. Also, that was in dev. Do you see 404s in dev or prod?

**Comment by bntzio** [comment]
Hey @tscanlin sorry for the late reply.

Yup the 404s appear on dev, but I just tried it with `next export` on prod and it's working fine! 👍

**Comment by tscanlin** [comment]
The PR is now merged and I made a minor release with this change `1.1.0`. Thanks! :)
